[project]
name = "repl-nix-nba-rating-visualizer"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "nba-api>=1.6.1",
    "pandas>=2.2.3",
    "streamlit==1.28.2",
]
